redux migration
ostannya/text-compare pull request #6
Opened 2021-07-15 12:40 UTC by ostannya

2021-07-16 06:16 UTC, delfrrr commented on src/components/Home.js
> +      store.dispatch(identical())
1. One event handler -> one action
2. No implicit dependencies between actions
3. If one action triggers another action, then thunk must be used

2021-08-02 06:49 UTC, delfrrr requested changes

2021-08-02 06:49 UTC, delfrrr commented on src/components/Home.js
>              onChange={this.handleChange}
Does not do anything

2021-08-02 06:49 UTC, delfrrr commented on src/components/Home.js
> +    store.dispatch(valueChange(this.props.original, this.props.changed))
does not do anything and would not work as uses previous values

2021-08-02 06:49 UTC, delfrrr commented on src/components/Input.js
> +    store.dispatch(valueChange(this.original.current.value, this.changed.current.value))
Does not need referrer in this component

2021-08-20 05:54 UTC, delfrrr commented on package.json
> +    "@reduxjs/toolkit": "^1.6.0",
🤔

2021-08-20 05:54 UTC, delfrrr commented on src/components/Home.js
> +                    diffArray={this.props.diffArray} onMenuClick={this.handleMenuClick} onLowercase={this.handleLowercase}
* `Toolbar` should not depend on props which can be taken from `store`
* it makes sense to incapsulate event handlers into the `Toolbar`

2021-08-20 05:54 UTC, delfrrr commented on src/components/Home.js
> +                    diffArray={this.props.diffArray} onMenuClick={this.handleMenuClick} onLowercase={this.handleLowercase}
Same for elements below

2021-08-21 07:15 UTC, delfrrr commented on src/components/Input.js
> +    this.handleOriganalChange = this.handleOriganalChange.bind(this)
not nececerly

2021-08-21 07:19 UTC, delfrrr commented on src/redux/actions.js
> +    type: DIFF_ARRAY,
action type and action creator naming mismatch

2021-08-21 07:20 UTC, delfrrr commented on src/redux/actions.js
> +      dispatch({ type: COMPARE })
code duplication

2021-08-21 07:23 UTC, delfrrr commented on src/redux/actions.js
> +    dispatch(notIdentical())
fasle logic

2021-08-21 07:24 UTC, delfrrr commented on src/redux/reducers.js
> +  switch (action.type) {
identical logic should be here

2021-08-23 09:12 UTC, ostannya commented on src/components/Input.js
> +    this.handleOriganalChange = this.handleOriganalChange.bind(this)
+ this.handleCompare in Home.js

2021-08-28 07:13 UTC, delfrrr commented on src/redux/reducers.js
> +export function result (state = false, action) {
unclear name; for example `showResult` is better

2021-08-28 07:18 UTC, delfrrr commented on src/redux/reducers.js
> +    case RESULT:
`RESULT` and `NO_RESULT` does not represent any event or user intent

2021-08-28 07:30 UTC, delfrrr commented on src/redux/actions.js
> +    dispatch(valueChange('', ''))
Logic should be in reducer

2021-08-28 07:34 UTC, delfrrr commented on src/redux/actions.js
> +function diffCompare (original, changed) {
what's different with `compare`?

2021-09-02 10:27 UTC, ostannya commented on src/components/Toolbar.js
> +    store.dispatch(lowercase(this.props.original, this.props.changed))
does not need to pass variables which can be taken frm store

2021-09-02 10:27 UTC, ostannya commented on src/redux/actions.js
> +export function compare (original, changed) {
does not require input params which can be taken from store

2021-09-03 06:06 UTC, delfrrr approved these changes

2021-09-03 06:08 UTC, merged